server:
  port: 8666
spring:
  application:
    name: zuul
eureka:
 client:
  service-url:
   defaultZone: http://server1:8764/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/
zuul:
 routes:
  web-service:
   path: /**
   serviceId: fegin

