server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    registerWithEureka: false #false:不作为一个客户端注册到注册中心
    fetchRegistry: false #为true时，可以启动，但报异常：Cannot execute request on any known server
    service-url:
      defaultZone: http://127.0.0.1:8888
  instance:
    ip-address: true

#后端的配置既可以是"serviceId"(对于服务发现中的服务而言), 也可以是"url"(对于物理地址)
zuul:
  prefix: /techouse #为zuul设置一个公共的前缀
  ignoredServices: '*' #忽略所有请求
  routes:
    users: #随便定义，当不存在serviceId时，默认该值为serviceId（就是注册服务的名称，属性spring.application.name）
      path: /user/**
#      serviceId: users
      url: https://www.baidu.com/

ribbon:
  eureka:
    enabled: false #配置zuul路由时用将此属性设置为false

cloud-client:
  ribbon:
    listOfServers: 127.0.0.1:8800 #为cloud-client服务指定一组服务地址，应该是用于负载均衡
