server:
  port: 8777
eureka:
  client:
    service-url: http://127.0.0.1:8888
spring:
  cloud:
    config:
      server:
        git:
          uri:
          search-paths: /**
      label: master
      username: zzq
      password: zzq144091

