server:
  port: 8777
eureka:
 client:
  service-url:
   defaultZone: http://server1:8764/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/18770911080/config
      label: master
  application:
    name: config

