server:
  port: 8777
eureka:
  client:
    zzq.ribbon.service-url: http://127.0.0.1:8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/18770911080/Springboot-Architecture
          search-paths: /**
      label: master
      username: zzq
      password: zzq144091

